#!/bin/sh
#
# Starts the avalonia playground app in /opt/publish/
#

start() {
	echo TIMAMI_NET: Starting application:
    (sh /opt/StartApplication.sh & )
}

stop() {
	printf "TIMAMI_NET: Stopping application: "
    killall dotnet
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?